Add transform (#231)
* Add transforms to SIMPL

Transforms are added a part of the geometry object.
Transforms can be simple transforms objects. They contain the following
data:
-Parameters: Parameters describing the transform.
-FixedParameters: Additional parameters, such as the center of rotation.
-TransformTypeAsString: String describing the transform type and its parameters types.
-MovingName: String saving the moving space name.
-ReferenceName: String saving the target space name.

Transforms are saved as part of the DREAM3D HDF5 file.

Filters to convert transforms from and to ITK filters have also been added.

* ENH: Apply clang-format to Constants.h

Constants.h was modified by PR, but a lot of the changes by clang-format
are touching code that was not modified in this PR, thus this separate
commit.

* STYLE: Separate template parameters and method

* COMP: Do not use SmartPointer's in ITK Transform filters

To address:

.dir/Testing/SIMPLUnitTest.cpp.o.d -o SIMPLView/SIMPL/SIMPLib/CMakeFiles/SIMPLUnitTest.dir/Testing/SIMPLUnitTest.cpp.o -c SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp
In file included from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:43:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DITransformContainerTest.cpp:55:13: error: no matching member function for call to 'SetInput'
    filter->SetInput(itkAffine);
    ~~~~~~~~^~~~~~~~
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DITransformContainer.h:58:16: note: candidate function not viable: no known conversion from 'SmartPointer<itk::AffineTransform<float, 3>::Self>' to 'const SmartPointer<itk::TransformBaseTemplate<float>::Self>' for 1st argument
  virtual void SetInput(const typename ITKTransformType::Pointer& transform);
               ^
/home/matt/src/ITK/Modules/Core/Common/include/itkProcessObject.h:524:16: note: candidate function not viable: requires 2 arguments, but 1 was provided
  virtual void SetInput(const DataObjectIdentifierType & key, DataObject *input);
               ^
In file included from SIMPLView/SIMPL/SIMPLib/Testing/SIMPLUnitTest.cpp:43:
/home/matt/src/SIMPL/Source/SIMPLib/ITK/Testing/Cxx/itkTransformToDream3DITransformContainerTest.cpp:70:13: error: no matching member function for call to 'SetInput'
    filter->SetInput(ct);
    ~~~~~~~~^~~~~~~~
/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkTransformToDream3DITransformContainer.h:58:16: note: candidate function not viable: no known conversion from 'SmartPointer<itk::CompositeTransform<float, 3>::Self>' to 'const SmartPointer<itk::TransformBaseTemplate<float>::Self>' for 1st argument
  virtual void SetInput(const typename ITKTransformType::Pointer& transform);
               ^
/home/matt/src/ITK/Modules/Core/Common/include/itkProcessObject.h:524:16: note: candidate function not viable: requires 2 arguments, but 1 was provided
  virtual void SetInput(const DataObjectIdentifierType & key, DataObject *input);